partition_to_port:
- system
- system_ext
- product
- my_product
- my_engineering
- my_company
- my_carrier
- my_region
- my_heytap
- my_stock
- my_preload
- my_bigball
- my_manifest
possible_super_list:
- system
- system_ext
- product
- vendor
- odm
- system_dlkm
- vendor_dlkm
- my_product
- my_engineering
- my_company
- my_carrier
- my_region
- my_heytap
- my_stock
- my_preload
- my_bigball
- my_manifest
repack_with_ext4: true
super_extended: false
pack_with_dsu: false
pack_method: erofs
ddr_type: ddr4
reusabe_partition_list:
- odm
- vendor
- system_dlkm
- vendor_dlkm
system_dlkm_enabled: true
vendor_dlkm_enabled: true
